eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
    fetch-registry: true
    register-with-eureka: true
    
    
microservices:
  order-food-service:
    endpoints:
      endpoint:
        uri: http://order-food-service/orders

  payment-service:
    endpoints:
      endpoint:
        uri: http://payment-service/doPayment
